[project]
name = "point-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aerich>=0.9.1",
    "aiobotocore>=2.23.0",
    "async-lru>=2.0.5",
    "asyncpg>=0.30.0",
    "cryptography>=45.0.5",
    "faker>=37.4.0",
    "fastapi>=0.116.1",
    "fastapi-pagination>=0.13.3",
    "notebook>=7.4.4",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "pydantic-settings>=2.10.1",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.20",
    "tomlkit>=0.13.3",
    "tonutils>=0.5.0",
    "tortoise-orm>=0.25.1",
    "uvicorn>=0.35.0",
]

[tool.aerich]
tortoise_orm = "point.config.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."
