[project]
name = "point"
version = "0.1.0"
description = "Main point api servise"
requires-python = ">=3.13"
dependencies = [
    "aerich>=0.9.2",
    "aiobotocore>=3.1.0",
    "aiogram>=3.22.0",
    "aiolimiter>=1.2.1",
    "async-lru>=2.0.5",
    "asyncpg>=0.31.0",
    "black>=0.9.1",
    "cryptography>=46.0.3",
    "faker>=40.1.0",
    "fastapi>=0.128.0",
    "fastapi-pagination>=0.15.5",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "pydantic-settings>=2.12.0",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.21",
    "quick-i18n>=0.1.2",
    "tomlkit>=0.13.3",
    "tonutils>=0.5.6",
    "tortoise-orm>=0.25.3",
    "uvicorn>=0.40.0",
    "point-shared",
]

[tool.uv.sources]
point-shared = { path = "./../point-shared", editable = true }

[tool.aerich]
tortoise_orm = "point.config.TORTOISE_ORM"
location = "./migrations"
src_folder = "./src"
