[project]
name = "point"
version = "0.1.0"
description = "Main point api servise"
requires-python = ">=3.13"
dependencies = [
    "aerich>=0.9.2",
    "aiobotocore>=3.2.0",
    "aiogram>=3.25.0",
    "aiolimiter>=1.2.1",
    "async-lru>=2.2.0",
    "asyncpg>=0.31.0",
    "black>=26.1.0",
    "cryptography>=46.0.5",
    "faker>=40.5.1",
    "fastapi>=0.134.0",
    "fastapi-pagination>=0.15.10",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "pydantic-settings>=2.13.1",
    "pytest>=8.0.0",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.22",
    "quick-i18n>=0.1.2",
    "tomlkit>=0.14.0",
    "tonutils<2.0.0", # TODO: migrate on v2
    "tortoise-orm>=0.25.4", # migrate to >= 1.0.0 - breaking changes
    "uvicorn>=0.41.0",
    "point-shared",
]

[tool.uv.sources]
point-shared = { path = "./../point-shared", editable = true }

[tool.aerich]
tortoise_orm = "point.config.TORTOISE_ORM"
location = "./migrations"
src_folder = "./src"
